# Generated by Django 3.0.1 on 2020-01-05 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinyls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='genre',
            new_name='genres',
        ),
    ]
