# Generated by Django 3.0.1 on 2020-01-14 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vinyls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcartitem',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='shopping_cart', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
