# Generated by Django 3.0.1 on 2020-01-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinyls', '0002_auto_20200114_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
