# Generated by Django 3.0.1 on 2019-12-29 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vinyls', '0002_auto_20191229_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['artist']},
        ),
        migrations.AlterField(
            model_name='shoppingcartitem',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart_items', to='vinyls.Album'),
        ),
    ]
